language: c
script: bash -ex .travis-ci.sh
cache:
  apt: true
  directories:
  - ~/.opam
env:
  matrix:
    - OCAML_VERSION=latest PACKAGE=packet
notifications:
  irc:
    channels:
      - "irc.freenode.net#frenetic"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}): %{message}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: always
