language: c
script: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
env:
  matrix:
    - OCAML_VERSION=latest PACKAGE=packet
notifications:
  irc:
    channels:
      - "irc.freenode.net#frenetic"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}): %{message}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: always
